name: 构建可执行程序

on:
  # 手动触发构建
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v1.0.0)'
        required: true
        default: 'v1.0.0'
  # 发布版本时自动触发
  release:
    types: [created]

jobs:
  build:
    name: 构建Windows程序
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Create version file
      run: |
        if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            "${{ github.event.inputs.version }}" | Out-File -FilePath version.txt
        } else {
            "${{ github.ref_name }}" | Out-File -FilePath version.txt
        }
        
    - name: Rename source file
      run: |
        Copy-Item "视频生成字幕并翻译.py" -Destination "video-subtitle-translator.py"
        
    - name: Build executable
      run: |
        $version = Get-Content version.txt
        $outputName = "video-subtitle-translator_${version}"
        pyinstaller --noconfirm --onefile --windowed --icon "app.ico" `
          --add-data "app.ico;." `
          --add-data "version.txt;." `
          --name "$outputName" `
          "video-subtitle-translator.py"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: video-subtitle-translator-${{ github.sha }}
        path: dist/*.exe
        
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.exe
        
    - name: Create release (Manual)
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: 发布版本 ${{ github.event.inputs.version }}
        body: |
          # 视频生成字幕并翻译 ${{ github.event.inputs.version }}
          
          ### 更新内容
          - 自动构建版本
          
          ### 使用前准备
          1. 安装 FFmpeg
             - Windows: 下载FFmpeg并添加到系统PATH
             - Linux: sudo apt-get install ffmpeg
             - MacOS: brew install ffmpeg
          
          ### 下载说明
          - Windows 64位可执行程序
          - 支持一键运行
          
          ### 系统要求
          - Windows 10/11 64位系统
          - 已安装FFmpeg并添加到系统PATH
          - 建议4GB以上内存
          - 如有GPU可加速处理
          
          ### 常见问题
          1. 提示"找不到FFmpeg"
             - 请确保已正确安装FFmpeg并添加到系统PATH
             - 可以在命令行中运行 ffmpeg -version 测试是否安装成功
          
        draft: true
        prerelease: false
        files: dist/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}